export const AUTENTICANDO_GOOGLE = "AUTENTICANDO_GOOGLE";
export const AUTENTICADO_CORREO = "AUTENTICADO_CORREO";
export const VALIDAR_TOKEN = "VALIDAR_TOKEN";
export const ELIMINAR_SESION = "ELIMINAR_SESION";
export const LISTADO_USUARIOS = "LISTADO_USUARIOS";
export const LISTADO_MENSAJE = "LISTADO_MENSAJE";
export const USUARIO_PRIVADOS = "USUARIO_PRIVADOS";
export const MENSAJES_PRIVADOS = "MENSAJES_PRIVADOS";