export const AUTENTICANDO_GOOGLE = "AUTENTICANDO_GOOGLE";
export const AUTENTICADO_CORREO = "AUTENTICADO_CORREO";
export const VALIDAR_TOKEN = "VALIDAR_TOKEN";
export const ELIMINAR_SESION = "ELIMINAR_SESION";